First complete draft

diff --git a/src/mfpqpcr b/src/mfpqpcr
--- a/src/mfpqpcr
+++ b/src/mfpqpcr
@@ -1,10 +1,10 @@
 #!/bin/bash
 
 # Performs in silico PCR to determine effectiveness and specificity
-# Usage: mfpqpcr -i protein_fasta -e env_directory [options,,,]
+# Usage: mfpqpcr -i primer_fasta -t target_gene_fasta [options,,,]
 # Input:
-#	primer_targets: an aligned fasta file with N characters removed
-#	env_directory: a directory containing the metagenomes to search against.
+#	primer_fasta: an primer fasta summarized from rdp output (format of the primer ID need to meet the request of `get_pcr_product.py`)
+#	target_gene_fasta: a nucleotide fasta with the genes that the primers can potentially target 
 # Outputs:
 #	primer_targets.primers.out: the raw output from RDP's PrimerDesign software
 #	primer_targets.primers.fa: the probes from RDP's PrimerDesign software formatted
@@ -15,12 +15,13 @@
 bold=$(tput bold)
 normal=$(tput sgr0)
 
-primer_targets=$1
+primer=$1
+target=$2
 
 
 die() {
 	printf 'ERROR: %s\n' "$1" 
-    printf 'See mfpqpcr -h for help.' >&2
+    	printf 'See mfpqpcr -h for help.\n' >&2
 	exit 1
 }
 
@@ -32,25 +33,23 @@ ${bold}MetaFunPrimer: qPCR${normal}
 	of primers.
 
 ${bold}Usage:${normal}
-	mfpqpcr -i <primers.fa> -e <env_directory> [options...]
+	mfpqpcr -i <primers.fa> -t <targets.fa> [options...]
 
 ${bold}Inputs:${normal}
 	- primers.fa: Fasta format file containing primer pairs for testing
-	- env_directory: Directory containing reference files
+	- targets.fa: Fasta format file containing nucleotide sequences of genes that can potentially be targeted by primers
 
 ${bold}Outputs:${normal}
 
 ${bold}Example:${normal}
-	mfpcluster -i fungene_9.6_amoA_AOB_1205_unaligned_protein_seqs.fa 
+	mfpqpcr -i primers.fa -t targets.fa
 
 ${bold}Options:${normal}
 	${bold}-i, --in <filename>${normal}	
 		Fasta format file containing primer pairs for testing
-	${bold}-b, --bg <filename>${normal}	
-		Fasta format file containing reference sequences
+	${bold}-t, --target <filename>${normal}	
+		Fasta format file containing nucleotide sequences that can potentially be targeted by primers
 	${bold}-o, --out <filename>${normal}	
-		String filename for where to save results. Defaults to <input_fasta>.products
-	${bold}-m, --mode [e, s]${normal}	
 		String filename for where to save results. Defaults to <input_fasta>.products
 	${bold}-h, --help${normal}	
 		Display this message
@@ -63,7 +62,7 @@ if (($# == 0)); then
 fi
 
 
-while getopts ":hi:o:b:e:-:" opt; do
+while getopts ":hi:o:t:-:" opt; do
   case ${opt} in
 	h ) 
 		usage
@@ -75,8 +74,8 @@ while getopts ":hi:o:b:e:-:" opt; do
 	i )
 		input_file=$OPTARG
 	;;
-	e ) 
-		env_dir=$OPTARG
+	t ) 
+		target=$OPTARG
 	;;
 	- )	
 		LONG_OPTARG="${OPTARG#*\s}"
@@ -84,32 +83,38 @@ while getopts ":hi:o:b:e:-:" opt; do
 			in )
 				eval "input_file=\"\$$OPTIND\""
 				if [ -z "$input_file" ]; then
-					die "Input file required for argument --in"
+					die "Input file (primer sequences) required for argument --in"
 				fi
 				if [ ! -f "$input_file" ]; then
 					die "Input file $input_file does not exist." 
 				fi
 				shift
 			;;
-			env )
-				eval "env_dir=\"\$$OPTIND\""
-				if [ -z "$env_dir" ]; then
-					die "Input required for argument --env"
+			target )
+				eval "target=\"\$$OPTIND\""
+				if [ -z "$target" ]; then
+					die "Input required for argument --target"
 				fi
 				# if [ ! -f "env_dir" ]; then
 				# 	echo "Input file $env_dir does not exist." >&2; exit 2
 				# fi
 				shift
 			;;
-			out )	
+			out_dir )	
 				eval "outdir=\"\$$OPTIND\""
 				if [ -z "$outdir" ]; then
-					die "Output directory required for argument --out" 
+					die "Output directory required for argument --out_dir" 
 				fi
 				# if [ ! -f "input_file" ]; then
 				# 	echo "Input file $input_file does not exist." >&2; exit 2
 				# fi
 				shift
+			;;
+			out_file )
+				eval "output_file=\"\$$OPTIND\""
+				if [ -z "$output_file" ]; then
+					die "Output file name is required for argument --out_file"
+				fi
 			;;
 			help ) 
 				usage
@@ -128,32 +133,84 @@ while getopts ":hi:o:b:e:-:" opt; do
 done
 
 if [ ! "$input_file" ]; then
-    die "Input file (protein fasta) required [-i | --in]"
+	die "Input file (primer sequences) required [-i | --in]"
 fi
+
+if [ ! -f "$input_file" ]; 
+then
+	die "Primers input $target does not exist."
+fi
+
 
 if [ ! "$outdir" ]
 then
-    outdir="$input_file.diamond_results"
+	outdir="$input_file.pcr_results"
 fi
-
-if [ ! "$env_dir" ]
-then
-	die "Reference directory required [-e | --env]"
-fi
-
-if [ ! -d "$env_dir" ]
-then
-    die "Reference directory $env_dir does not exist."
-fi
-
-
-echo "Input: $input_file"
-echo "Environment: $env_dir"
-echo "Output directory: $outdir"
 
 if [ ! -d "$outdir" ]
 then
 	mkdir $outdir
 fi
-cd $outdir
+
+
+
+if [ ! "$target" ]
+then
+	die "Target genes required [-t | --target]"
+fi
+
+if [ ! -f "$target" ]
+then
+	die "Target genes input $target does not exist."
+fi
+
+
+echo "Input: $input_file"
+echo "Target: $target"
+echo "Output directory: $outdir"
+
+
+#cd $outdir
+
+if [ ! "$output_file" ]
+then
+	output_file="$input_file.out"
+fi
+echo "The current working directory: $PWD"
+
+#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+#echo "The script directory: $DIR"
+#python "$DIR/modi_get_pcr_product.py" "$input_file" "$target" > "$outdir/$output_file"
+#modi_get_pcr_product.py "$input_file" "$target" > "$outdir/$output_file"
+
+get_pcr_product.py "$input_file" "$target" > temp
+
+# this script will generate a file mfpqpcr.log which contains the genes that can be targeted by the final primer sets
+filter_primers_output.py temp > temp_out1
+
+# this is the output primer nucleotide sequence fasta file
+awk 'BEGIN{FS="\t"; OFS="\n";} {if (NF==5) print ">"$1, $2, ">"$3, $4; }' temp_out1 > "$outdir/$output_file.fa"
+
+# this is the complete output file including information such as primer pair, product length, and genes that can be target by each primer pair
+mv temp_out1 "$outdir/$output_file"
+
+# this is the total number of genes that can be targeted by final primer sets
+numTar="$(sed -n '$=' mfpqpcr.log)"
+
+# this is the total number of input target genes 
+nGene="$(sed -n '$=' $target)"
+numGene=$(($nGene / 2))	#should always be an integer
+
+# this is the percentage of genes that primer sets can target
+perc=$(echo "${numTar}/${numGene}*100" | bc -l)
+sim_perc=$(printf "%.2f" $perc)
+
+seps="--------------------------------------------------"
+sed "1 s/^/The resulting primer set amplifies $numTar out of $numGene ($sim_perc%) target genes:\n$seps\n/" mfpqpcr.log > "$outdir/mfpqpcr.log"
+
+sed -i "1 i MetaFunPrimer: qPCR\n-i: "$input_file"\n-t: "$target"" "$outdir/mfpqpcr.log"
+
+rm mfpqpcr.log
+
+rm temp
 
