Update argument parsing and checking

diff --git a/src/mfpsearch b/src/mfpsearch
--- a/src/mfpsearch
+++ b/src/mfpsearch
@@ -17,18 +17,22 @@ normal=$(tput sgr0)
 
 primer_targets=$1
 
+
 die() {
-	printf 'ERROR: %s\nExiting...' "$1" >&2
+	printf 'ERROR: %s\n' "$1" 
+    printf 'See mfpsearch -h for help.' >&2
 	exit 1
 }
-
 
 usage() {
 cat << EOF 
 
 ${bold}MetaFunPrimer: Search${normal}
-	Prepares and submits BLAST searches of an input file against a directory
-	of metagenome files.
+	Prepares and submits BLAST searches of an input FASTA file against a directory
+	of reference files.
+
+    Currently requires that the input file be a protein fasta file
+    and the reference files be nucleotide fastas.
 
 ${bold}Usage:${normal}
 	mfpdesign -i <protein_sequences> -e <env_directory> [options...]
@@ -77,9 +81,8 @@ while getopts ":hi:o:b:e:-:" opt; do
   case ${opt} in
 	h ) 
 		usage
-		echo "Exiting..."
 		exit 1
-      	;;
+    ;;
 	o )
 		outdir=$OPTARG
 	;;	
@@ -93,21 +96,19 @@ while getopts ":hi:o:b:e:-:" opt; do
 		LONG_OPTARG="${OPTARG#*\s}"
 		case ${OPTARG} in
 			in )
-				echo "$OPTARG"	
 				eval "input_file=\"\$$OPTIND\""
-				if [ -z "input_file" ]; then
-					echo "Input file required for argument --in" >&2; exit 2
+				if [ -z "$input_file" ]; then
+					die "Input file required for argument --in"
 				fi
-				# if [ ! -f "input_file" ]; then
-				# 	echo "Input file $input_file does not exist." >&2; exit 2
-				# fi
+				if [ ! -f "$input_file" ]; then
+					die "Input file $input_file does not exist." 
+				fi
 				shift
 			;;
 			env )
-				echo "$OPTARG"	
 				eval "env_dir=\"\$$OPTIND\""
-				if [ -z "env_dir" ]; then
-					echo "Input file required for argument --in" >&2; exit 2
+				if [ -z "$env_dir" ]; then
+					die "Input required for argument --env"
 				fi
 				# if [ ! -f "env_dir" ]; then
 				# 	echo "Input file $env_dir does not exist." >&2; exit 2
@@ -116,8 +117,8 @@ while getopts ":hi:o:b:e:-:" opt; do
 			;;
 			out )	
 				eval "outdir=\"\$$OPTIND\""
-				if [ -z "outdir" ]; then
-					echo "Output directory required for argument --out" >&2; exit 2
+				if [ -z "$outdir" ]; then
+					die "Output directory required for argument --out" 
 				fi
 				# if [ ! -f "input_file" ]; then
 				# 	echo "Input file $input_file does not exist." >&2; exit 2
@@ -129,20 +130,20 @@ while getopts ":hi:o:b:e:-:" opt; do
 				exit 1
 			;;
 			* )
-				echo "Invalid option: $LONG_OPTARG"
-				usage
-				exit 1
+				die "Invalid option: $LONG_OPTARG"
 			;;
 
 		esac
 	;;
     	\? )
-		echo "Invalid option: $OPTARG"
-		usage
-		exit 1
+		    die "Invalid option: $OPTARG"
       	;;
   esac
 done
+
+if [ ! "$input_file" ]; then
+    die "Input file (protein fasta) required [-i | --in]"
+fi
 
 if [ ! "$outdir" ]
 then
@@ -151,8 +152,14 @@ fi
 
 if [ ! "$env_dir" ]
 then
-	die "Environment directory required [-e | --env]"
+	die "Reference directory required [-e | --env]"
 fi
+
+if [ ! -d "$env_dir" ]
+then
+    die "Reference directory $env_dir does not exist."
+fi
+
 
 echo "Input: $input_file"
 echo "Environment: $env_dir"
@@ -164,7 +171,6 @@ then
 fi
 cd $outdir
 
-# Make dbs
 printf "\nMaking DIAMOND database...\n\n"
 
 diamond makedb --in ../$input_file -d $input_file
@@ -178,7 +184,7 @@ printf "\nCreating job commands..."
 
 for fin in $env_dir/*.{fasta,fa,fastq,faa}
 do
-	echo "diamond blastx --db ../$input_file --query $fin --out ../$(basename $fin).m8 --id 96"
+	echo "diamond blastx --db ../$input_file --query $fin --out ../$(basename $fin).m8 --id 97"
 done > commands.diamond.txt
 
 split -a 3 -dl 20 --additional-suffix=.sb commands.diamond.txt job.diamond.
@@ -186,13 +192,13 @@ split -a 3 -dl 20 --additional-suffix=.sb commands.diamond.txt job.diamond.
 for fin in *.sb
 do
 	current_job=$(echo $fin | cut -d '.' -f 3)
-	printf "%s\n\n%s\n\n" "$(job_header $current_job)" "$(cat $fin)" > $fin
+	printf "%s\n\n%s\n%s\n\n" "$(job_header $current_job)" "$(cat $fin)" "EOF" > $fin
 	echo "update_job_status $current_job \"Finished: \$(date +'%H:%M %m\/%d\/%y')\"" >> $fin
 	echo "$current_job" >> job.checklist.tsv
 done
 
-printf "\nDone."
-printf "\nSubmitting jobs..."
+printf "Done."
+echo "Submitting jobs..."
 
 for fin in *.sb
 do 
